### ISSUE TITLE
Error in FindLongestSeq

### ISSUE THREAD

**Issue by haruosuz** [sborstein/AnnotationBustR#18]
I followed the steps in the vignette https://github.com/sborstein/AnnotationBustR/blob/master/vignettes/AnnotationBustR-vignette.md

Enclosed are my R code and log file.
[Rcode.txt](https://github.com/sborstein/AnnotationBustR/files/4018084/Rcode.txt)
[log.txt](https://github.com/sborstein/AnnotationBustR/files/4018083/log.txt)

I got the following error messages.
```r
> my.longest.seqs<-FindLongestSeq(accessions)#Run the FindLongestSeq function
Error in file(file, "r") : 
  cannot open the connection to 'https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=nucleotide&id=c("MK829671&rettype=fasta&retmode=text'
In addition: Warning message:
In file(file, "r") :
  cannot open URL 'https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=nucleotide&id=c("MK829671&rettype=fasta&retmode=text': HTTP status was '400 Bad Request'
```

When deleting `c("`, 
I can open the URL 'https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=nucleotide&id=MK829671&rettype=fasta&retmode=text' with my browser (Chrome).

**Comment by sborstein** [comment]
You must call the vector of accessions and not the data frame itself. As it was written, you were reading in a table for Pristimantis and did not specify a vector. I have edited the vignette so it is more clear and have changed the examples to highlight this. As the function itself is working fine, I am closing the issue.
