### ISSUE TITLE
invalid request:"unknown accession number at (^): \"AC

### ISSUE THREAD

**Issue by ptitle** [sborstein/AnnotationBustR#24]
Hi,

I haven't been able to get the AnnotationBust function to work for a set of accessions I'm interested in. I realize this seems to be an issue with seqinr, but perhaps you can provide some suggestions. Thanks!

```
my.seqs <- AnnotationBust(Accessions= 'ON682400', Terms= mtDNAterms, TranslateCode=2, DuplicateSpecies=FALSE, TidyAccessions=TRUE)
[1] "Working On Accession ON682400 Crocidura_suaveolens_gueldenstaedtii"
Error in seqinr::query(paste0("AC=", new.access)) : 
  invalid request:"unknown accession number at (^): \"AC
```

**Comment by sborstein** [comment]
Sorry for the delay. Easy explaination for this one and yes, it is completely related to the seqinr dependency.

Unfortunately, seqinr has not had an update to the ACNUC database in quite some time. The current version uses GenBank Release 246 (15 October 2021). Your sequence `ON682400` appears to have been released in 2022, so it would not be accessible via `seqinr`. You can get this info via `seqinr` by doing the following:

```seqinr::choosebank(infobank = TRUE)```

I have found an alternate way to access subsequences and am working on replacing `seqinr` as a dependency for `AnnotationBustR` as `seqinr` it is not using current GenBank releases and users (as well as myself) have had issues with connecting to the ACNUC servers through seqinr as it seems unstable, especially when querrying many accessions. However, I just started a new faculty position, so I can not provide a time for a release of an update alleviating this.

I'm going to close the issue as this is an issue with `seqinr`, but hopefully that answers our question.

Best,
-Sam

**Comment by ptitle** [comment]
I understand, thanks!
