### ISSUE TITLE
Error in `FindLongestSeq `  command

### ISSUE THREAD

**Issue by NILamprou** [sborstein/AnnotationBustR#25]
Greetings, 
I am using this package in order to pull a large amount of sequences. This is my script so far 
`library(AnnotationBustR)
library(reutils)

demo.search <- esearch(term = "Mollusca[orgn] and COI[title]", db = 'nuccore', usehistory = TRUE)  # Search
accessions <- efetch(demo.search, rettype = "acc", retmode = "text", outfile = "COI.txt")
accessions <- strsplit(accessions, "\n")[[1]]  # Split the character vector using "\n"

my.longest.seqs<-FindLongestSeq(accessions)#Run the FindLongestSeq function`

The error message I get is the following 
`Error in file(file, "r") : 
  cannot open the connection to 'https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=nucleotide&id=COI&rettype=fasta&retmode=text'
In addition: Warning message:
In file(file, "r") :
  cannot open URL 'https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=nucleotide&id=COI&rettype=fasta&retmode=text': HTTP status was '400 Bad Request'`

Is this a package issue, server issue or is my data request way too large for this platform? Thanks in advance.

**Comment by sborstein** [comment]
This is an issue you are having with `reutils:::efetch` and connecting to it. I was not able to replicate the issue as I was able to complete the request without issues

Note that with `efetch` as your request is large and you use the outfile argument, it is not storing the retrieved accessions in R, but rather writing them to a file you specified `COI.txt`. You will need to read the `COI.txt` back into R and supply it the `FindLongestSeq` function with the vector of accessions in `COI.txt`.

Given this, I am closing the request.
